---
title: "_quarto"
format: html
editor: visual
author: Megan Hessel
theme: cosmo
project:
  output-dir: ../docs
execute: 
  warning: false
---

## Background

In 2000, Dr. Schaefer and colleagues investigated chemical fluxes in the Luquillo Experimental Forest watersheds of Puerto Rico following Hurricane Hugo. Hurricane Hugo was a distructive category 4 storm that passed through Puerto Rico on September 18, 1998 (Schaefer, McDowell, Scatena, and Asbury 2000) .

This GitHub repository reproduces a similar time series plot from their work, focusing on the Bisley watershed.

SCHAEFER, DOUGLAS. A.; McDOWELL, WILLIAM H.; SCATENA, FREDRICK N.; ASBURY,CLYDE E. 2000. Effects of hurricane disturbance on stream water concentrations and fluxes in eight tropical forest watersheds of the Luquillo Experimental Forest, Puerto Rico. Journal of Tropical Ecology 16:189±207.

## Data

Since the 1980s, stream water samples have been collected weekly at the Luquillo Experimental Forest in Puerto Rico, measuring chemical concentrations, average stream flow, pH, and more.

All the data accumulated can be found on the EDI Data Portal: <https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-luq.20.4923064>

However, for replication of only Figure 3 within the paper, four csvs are required (Quebrada 1, 2, and 3-Bisley and Puente Roto Mameyes (MPR) Chemistry Data) which can be found in the EDI Data Portal or the data folder within the repository.

## Methods

\(1\) Download, clean, and filter the data.

\(2\) Using the moving average function, calculate a 9 week moving average for all chemical concentrations at each site. Then combined the individual tables into a single main data frame.


```{r}
#| code-fold: true
#| echo: true

# Loading the cleaned and filtered data frames with the moving average calculations 
BQ1_data_ma <- readRDS(file = here::here("outputs", "BQ1.rds")) # this is where the rds file is saved
BQ2_data_ma <- readRDS(file = here::here("outputs", "BQ2.rds"))
BQ3_data_ma <- readRDS(file = here::here("outputs", "BQ3.rds"))
PRM_data_ma <- readRDS(file = here::here("outputs", "PRM.rds"))

# combining all the data frames together 
full_data <- rbind(BQ1_data_ma, BQ2_data_ma, BQ3_data_ma, PRM_data_ma)

```

\(4\) With all the data calculated and accumulated, create a multileveled time series plot using ggplots.

## Results

The replicated time series plot shows the various chemical concentrations changing overtime at different rivers in the Bisley watershed.

```{r}
#| echo: false 
#| fig-width: 15
#| fig-height: 15 

#download the library
library(ggplot2)

#defining the hurricane year 
hurrican_year <- as.Date("1989-09-18")

#...................Creating the individual graphs ......................

# Potassium graph 
k_plot <- ggplot(full_data, 
                 aes (x = sample_date, 
                      y = k_ma, 
                      color = sample_id)) + 
  geom_line() + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        legend.position = "none", 
        axis.text.y = element_text(size = 13), 
        axis.title.y = element_text(size = 18), 
        title = element_text(size = 23), 
        plot.caption = element_text(size = 14)) +
  geom_vline(xintercept = hurrican_year, color = "darkgrey", linetype = "dashed") +
  labs(y = "K mg l^(-1)", 
       title = "Chemical Concentrations in Bisley, Puerto Rico Streams", 
       subtitle = "Before and after Hurricane Hugo", 
       caption = "(a)") + 
  scale_color_manual(values = c("#D8AEDDFF", "#81C14B", "#F5D000FF", "#00A6A6"))


# NO3-N graph 
no3n_plot <- ggplot(full_data, 
                    aes (x = sample_date, 
                         y = no3n_ma, 
                         color = sample_id)) + 
  geom_line() + 
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        axis.text.y = element_text(size = 12), 
        axis.title.y = element_text(size = 17), 
        legend.text = element_text(size = 14), 
        legend.title = element_text(size = 17), 
        plot.caption = element_text(size = 14)) +
  geom_vline(xintercept = hurrican_year, color = "darkgrey", linetype = "dashed") +
  labs(y = "NO3-N ug^(-1)", 
       color = "Streams", 
       caption = "(b)") + 
  scale_color_manual(values = c("#D8AEDDFF", "#81C14B", "#F5D000FF", "#00A6A6"))

# Magnesium graph 
mg_plot <- ggplot(full_data, 
                  aes (x = sample_date, 
                       y = mg_ma, 
                       color = sample_id)) + 
  geom_line() +   
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        legend.position = "none", 
        axis.text.y = element_text(size = 13), 
        axis.title.y = element_text(size = 18), 
        plot.caption = element_text(size = 14)) +
  geom_vline(xintercept = hurrican_year, color = "darkgrey", linetype = "dashed") +
  labs(y = "Mg mg l^(-1)", 
       caption = "(c)") + 
  scale_color_manual(values = c("#D8AEDDFF", "#81C14B", "#F5D000FF", "#00A6A6"))


# Calcium graph 
ca_plot <- ggplot(full_data, 
                  aes (x = sample_date, 
                       y = ca_ma, 
                       color = sample_id)) + 
  geom_line()+   
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_blank(), 
        legend.position = "none", 
        axis.text.y = element_text(size = 13), 
        axis.title.y = element_text(size = 18), 
        plot.caption = element_text(size = 14)) +
  geom_vline(xintercept = hurrican_year, color = "darkgrey", linetype = "dashed") +
  labs(y = "Ca mg l^(-1)", 
       caption = "(d)") + 
  scale_color_manual(values = c("#D8AEDDFF", "#81C14B", "#F5D000FF", "#00A6A6"))


#NH4-N graph 
nh4n_plot <- ggplot(full_data, 
                    aes (x = sample_date, 
                         y = nh4n_ma, 
                         color = sample_id)) + 
  geom_line() + 
  theme(axis.title.x = element_blank(), 
        legend.position = "none", 
        axis.text.y = element_text(size = 13), 
        axis.title.y = element_text(size = 18), 
        axis.text.x = element_text(size = 20), 
        plot.caption = element_text(size = 14)) +
  geom_vline(xintercept = hurrican_year, color = "darkgrey", linetype = "dashed") +
  labs(y = "NH4-N ug^(-1)",
       x = "Years",
       caption = "(e)") + 
  scale_color_manual(values = c("#D8AEDDFF", "#81C14B", "#F5D000FF", "#00A6A6")) 



#.................. Combining the graphs .......................


library(patchwork) # load the library that allows plots to be on top of each other 
time_series_plot <- (k_plot / no3n_plot / mg_plot / ca_plot / nh4n_plot)

time_series_plot

```

The chemicals included in the study are (a) potassium, (b) nitrate-N, (c) magnesium, (d) calcium, (e) ammonium-N. The various colors represent different rivers within in the watershed. Lastly, the vertical dashed-line represents Hurricane Hugo's disruption.

The plot indicates that levels of potassium, nitrate-N, and magnesium increased sharply after the storm. Whereas, calcium concentrations did rise but at a more gradual rate. Due to a lack of data, ammonium-N concentration cannot be properly investigated.
